### ISSUE TITLE
Mac

### ISSUE THREAD

**Issue by AntoineRousseau97** [mr-sheg/orpl#1]
does it work on mac? :) your algorythm looks awesome and i would like to try it out with my Raman spectra!

**Comment by DrSheg** [comment]
Thanks :smile: 
I can't see any obvious reason why it would not work on OSX, but I do not have any macs to test it on.
Did you have a go at it?

**Comment by DrSheg** [comment]
I have just installed a VM of Catalina. Seems to work just fine ;)

![Screenshot_20230531_115309](https://github.com/mr-sheg/orpl/assets/27356351/04ae562d-f227-4c57-a366-4c2bf61cad57)

The installation steps are similar to windows (see guide from the readme). However, keep in mind that OSX comes with python 2.7 installed by default. This is not a good thing, as python 2.7 and python 3 are vastly different. In short, if you launch `python` from terminal on a mac, you'll get python 2.7 running. You need to run `python3` to have python 3.X.

Here's an overview of the installation of ORPL on a mac.

1. Install python 3 - download latest from https://www.python.org/
2. Run `python3 -m pip install orplib` from terminal
3. Launch ORPL- GUI from terminal by running `python3 -m orpl`

**Comment by AntoineRousseau97** [comment]
effectivement, ca fonctionne bien sur mac!
